### ISSUE TITLE
need to solve this problem!!

### ISSUE THREAD

**Issue by bitman09** [solguru310/dex-mev-arbitrage-bot#1]
i got this error.

```
Finished dev profile [unoptimized + debuginfo] target(s) in 1.02s
     Running target\debug\examples\crossed_pairs.exe
[STARTING]
thread 'main' panicked at D:\dex-mev-arbitrage-bot-main\src\dex_factory.rs:109:1
8:
called Result::unwrap() on an Err value: MiddlewareError { e: MiddlewareErro
r(JsonRpcClientError(JsonRpcError(JsonRpcError { code: -32603, message: "request
 failed or timed out", data: None }))) }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\crossed_pairs.ex
e` (exit code: 101)
```

how to fix this error?

**Comment by solguru310** [comment]
at first you have to check the JSON-RPC Endpoint.

**Comment by solguru310** [comment]
Your error message indicates that code encountered an issue when trying to execute Result::unwrap().
specifically, it failed due to a `JsonRpcClientError`
It means there was a problem communicating with a JSON-RPC server, either a timeout or the server not responding as expected.

you can follow below steps to solve this problem:
- confirm that the RPC endpoint you're connecting to is correct, accessible, and operational
- also you can run with
```
RUST_BACKTRACE=1
```

setting the environment variable 'RUST_BACKTRACE=1' will give you a more detailed stack trace
```
RUST_BACKTRACE=1 cargo run --example crossed_pairs
```

like this.

please try!

**Comment by bitman09** [comment]
Thanks for your help
